name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    - name: Start local server
      run: |
        nohup npm start &
        sleep 10 # ждем 10 секунд, чтобы сервер успел запуститься
        
    - name: Run Cypress tests
      run: npx cypress run
    
     
       
