name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Start local server
      run: npm start
        
    - name: Run Cypress tests
      run: npx cypress run --browser chrome
      
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
          name: cypress-reports
          path: cypress/reports
      # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: always()
      with:
          name: cypress-reports
          path: cypress/reports
     
     
       
