name: CI

on: [push]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      
    - name: Start local server 
      run: nohup npm start & npx -- wait-on http://127.0.0.1:3000 -t 20000
        
    - name: Run Cypress tests
      run: npx cypress run --browser chrome
      
    - name: Upload Cypress test reports
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/reports/html/index.html

     
     
     
       
     
     
     
       
