name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      
    - name: Start local server
      run: |
        nohup npm start &
        sleep 10 # ждем 10 секунд, чтобы сервер успел запуститься
        
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
          browser: chrome
     
       
