name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and Cypress run
      # https://github.com/cypress-io/github-action
      
      - name: Install dependencies
        run: npm install
        
      - name: Install Cypress
        run: npm install Cypress
        
      - name: Start local server
        run: npm start
        
      - name: Cypress run
        run: npx cypress run
        
       
